### ISSUE TITLE
search for entities and decorators

### ISSUE THREAD

**Issue by gg4u** [maxlath/wikidata-sdk#21]
How to search for images url and descriptions related to an entity?
E.g.
https://www.wikidata.org/w/api.php?action=wbsearchentities&search=transcription%20&format=json&language=en&type=item&continue=0

I would like to complete with images, to make a list with their own thumbnail.

**Comment by maxlath** [comment]
A description is available directly from the search results, but to get images, you need to access the claims with another request:
* collect the entities ids you got from the search: in your case `Q177900`, `Q207714`, `Q223868`, `Q1458203`, `Q25203627`, `Q33059448`, `Q2249643`
* query the entities data: `https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q177900|Q207714|Q223868|Q1458203|Q25203627|Q33059448|Q2249643&format=json&props=claims`
* parse the results' claims (you can use [`wdk.simplify.claims`](https://github.com/maxlath/wikidata-sdk/blob/master/docs/simplify_claims.md) for that) to get the filename of images on Commons, typically with the `P18` property (but not only: for instance, logo = `P154`, collage image = `P2716`)
* then, you can directly access a thumbnail from the filenames like so: `https://commons.wikimedia.org/w/thumb.php?width=200&f=MRNA.svg`

**Comment by gg4u** [comment]
Thank you @maxlath , you must have spent quite a time in the parser!

I am looking at claims, it is not simple to understand what properties refers to.

I looked at  `wdk.simplify.claims` : have you considered to allow fetch images ?
For that "typically" an image is P18, but also P154, P2716 .. how to know which properties are images?

Also, how to construct the url?
E.g. 
`P18":[{"mainsnak":{"snaktype":"value","property":"P18","hash":"d76b9e199406512a9ce894e4b9657185ef2c863d","datavalue":{"value":"MRNA.svg","type":"string"},"datatype":"commonsMedia"},"type":"statement","id":"Q177900$386453a2-428a-b8ca-3449-94b1ece2e344","rank":"normal"}]`

how do you know that the corresponding URI is `https://commons.wikimedia.org/w/thumb.php?width=200&f=` ?

And what would the uri be for other domains ?  Or all images is wikidata are expected to be hosted in `https://commons.wikimedia.org/w/thumb.php?` ?

**Comment by maxlath** [comment]
The main way to learn about properties of interest is to browse entities in your domain of interest and see which one are used by the community. Reading the properties discussion pages can help too (see for example [P18 _see also_ section](https://www.wikidata.org/wiki/Property_talk:P18)). Or you can browse all the properties using [propbrowse](https://tools.wmflabs.org/hay/propbrowse/) or [that property dump](https://github.com/maxlath/wikidata-edit/blob/master/lib/properties/properties.js)

I use `https://commons.wikimedia.org/w/thumb.php?width=200&f=` because that's the easiest thing to do to find an image URL, given a Commons media filename such as `MRNA.svg`. The alternative is to fetch more data about the media using [Wikimedia Commons API](https://tools.wmflabs.org/magnus-toolserver/commonsapi.php) (ex: https://tools.wmflabs.org/magnus-toolserver/commonsapi.php?image=MRNA.svg&thumbwidth=200 ) but that requires an additional request.

All images linked by P18 are hosted on https://commons.wikimedia.org: that's part of it's `CommonsMedia` datatype, linking to external images isn't really possible in Wikidata. That said, I have been playing around ways to find external images from Wikidata external ids: for instance, you can deduce Twitter avatar URLs from [P2002](https://wikidata.org/entity/P2002): `https://twitter.com/${username}/profile_image?size=original`

**Comment by gg4u** [comment]
That's neat references @maxlath - thank you!

**Comment by maxlath** [comment]
you're welcome :)
