### ISSUE TITLE
Feeding Wikidata

### ISSUE THREAD

**Issue by gg4u** [maxlath/wikidata-sdk#22]
@maxlath since you look expert of wikidata, I ll share with you an idea I have - happy to continue discussion via email or in PVT if interested.

I would like to allow the community (aka, the public) to feed wikidata with information of public interest, but that is still, in some how, provided as "premium" service.

I have been working in knowledge graphs and contextual research domain, and my point of view is that while data is redudant, insights are not, and I would like to facilitate and enable diverse type of people (and companies) to compute own analytics.

To do so, they need to access data.

I d like to leverage on crowd-sourced data, and use wikidata as the repository.

Does your tool allow to feed and store new entities and properties over wikidata?

I tried to contact them, but it is not so clear to me how the process work and would like to simplify.
The data I would like to focus on are data about companies around the world - a very very central aspect in enabling "decentralised" governance over economic networks.

___

P.s. if you are interested in, this is one of the application I designed to explore and make sense of knowledge networks - here applied to English Wikipedia http://nifty.works  - would like to applied to other economic networks like http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0025995

**Comment by maxlath** [comment]
[`wikidata-sdk`](https://github.com/maxlath/wikidata-sdk) is focused on read operations on Wikidata; for entity creation/edition, have a look to [`wikidata-edit`](https://github.com/maxlath/wikidata-edit)

Otherwise, I don't know much what to answer: creating entities in bulk should always be subject to a discussion with the community, either in the mailing list (for instance, you may find inspiration in the [current discussion around integrating data from 2.2 million German organisations](https://lists.wikimedia.org/pipermail/wikidata//2017-October/011235.html)), or in the chats, either the [general one](https://www.wikidata.org/wiki/Wikidata:Project_chat) or the one from the appropriate [sub-project](https://www.wikidata.org/wiki/Wikidata:WikiProjects): the [WikiProject Companies](https://www.wikidata.org/wiki/Wikidata:WikiProject_Companies) could fit.
