### ISSUE TITLE
what is promiseRequest?

### ISSUE THREAD

**Issue by alexan1** [maxlath/wikidata-sdk#31]
reading your documentation, I see code:

```
// see the "SPARQL Query" section above
var url = wdk.sparqlQuery(SPARQL)
promiseRequest(url)
.then(wdk.simplifySparqlResults)
.then((simplifiedResults) => { // do awesome stuffs here })
```

But I get the following error:

![image](https://user-images.githubusercontent.com/4028682/40525939-e1908318-5fa8-11e8-9baf-cf36cc3d6abb.png)

Where this promiseRequest came from?

**Comment by maxlath** [comment]
yep, sorry, this piece of doc is assuming some knowledge of [promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises), and at least one of the many ([[1](https://libraries.io/search?q=request+promise&platforms=NPM&sort=stars)], [[2](https://libraries.io/search?q=request+bluebird&platforms=NPM&sort=stars)]) libraries that bundle HTTP requests in promise object. In my own favorite (probably because I wrote it ;)), you can define `promiseRequest` like this:
```js
// after having installed the bluereq package with `npm i bluereq`
const breq = require('bluereq')
const promiseRequest = breq.get

promiseRequest(url)
.then(doYourThing)
```

**Comment by alexan1** [comment]
I know what are promises, just don/t understand why we should use some library for this, we have fetch (does it do the same?)

**Comment by maxlath** [comment]
@alexan1 in modern browsers, yes:
```js
const promiseRequest = url => fetch(url).then(res => res.json())
```
but not in Node.js

**Comment by alexan1** [comment]
okay, I don't use node.js anyway
